service: periodic-table

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2

package:
  exclude:
    - ./**
  include:
    - ./build/**

functions:
  getElements:
    handler: build/functions/elements.getElements
    events:
      - http: 
          path: elements
          method: get
  getElement:
    handler: build/functions/elements.getElement
    events:
      - http: 
          path: elements/{id}
          method: get
          request:
            parameters:
              paths:
                id: true